config/routes.rb
Rails.application.routes.draw do
  resources :interests
  resources :user_interestts
  devise_for :users


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  # root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :interest
end

app/models/interest.rb
class Interest < ApplicationRecord
    has_many :user_interests
    has_many :users, through: :user_interests
  
end

app/models/relation.rb
class Relation < ApplicationRecord
    has_many :interests
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_interestts
  has_many :interests, through: :user_interestts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :user
  belongs_to :interest
end

app/models/user_interestt.rb
class UserInterestt < ApplicationRecord
  belongs_to :user
  belongs_to :interest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
    
    def create
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @user_interestt = UserInterestt.all
    end

    

    
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
    before_action :set_interest, only: [:show, :edit, :update, :destroy]
    
    def index
        # @user_interestt = UserInterestt.all
        @user_interestt = current_user.user_interestts

    end
    def new
        @user_interestt = current_user.user_interestts

        @interest = Interest.new
    end
    def create
        @interest = Interest.where(link: interest_params[:link]).first_or_create(interest_params) 
        # @interest = Interest.create(interest_params)
        # @user_interestt = UserInterestt.create(user_id: current_user.id, interest_id: @interest.id)
        @user_interestt = UserInterestt.where(user_id: current_user.id, interest_id: @interest.id).first_or_create

    end
    
    def destroy
        
        @interestx.destroy
        # respond_to do |format|
        #   format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
        #   format. json { head :no_content }
        # end
    
    
    end

    def set_interest
        @interestx = UserInterestt.find(params[:id])

    end
    private
    def interest_params
        params.require(:interest).permit(:title, :description, :link, :image)
    end
end

app/controllers/user_interestts_controller.rb
class UserInteresttsController < ApplicationController
    before_action :set_interest, only: [:show]

    def show
        
    end
    
    def destroy
    @user_interestt = UserInterestt.find(params[:id])
    @user_interestt.destroy
    redirect_to interests_path
    end

    def set_interest
        @interestx = UserInterestt.find(params[:id])

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<main role="main">



      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">WeMatch People</h1>
          <p class="lead text-muted">Imagine that you find all your interests in one place, connect with in-common people and keep your stuff organized.</p>
          <p>
            <%# <a href="#" class="btn btn-primary my-2">Sign Up NOW!</a> %>
                 <%= link_to "Sign up NOW!", new_user_registration_path, :class=>"btn btn-primary my-2"%>

            <%# <a href="#" class="btn btn-secondary my-2">Want moor?</a> %>
          </p>
        </div>
      </section>

<div class="card-columns container" style="background-color: red"> <!-- START OF CARD-GROUP -->
   <% User.all.each do |user|%>

    <% user.user_interestts.each do |interest| %>
        <div class="card ">
        <%if interest.interest.image == "undefined" %>
                <h5 class="card-title"><%= interest.interest.title %></h5>
                <blockquote class="blockquote mb-0">
                <p class="card-text"><%= interest.interest.description %></p>

                </blockquote>
          
        <%else%>
            <img class="card-img-top" src="<%= interest.interest.image %>" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><%= interest.interest.title %></h5>
                <p class="card-text"><%= interest.interest.description %></p>
              </div>
       
        <%end%>
   </div>
              
      <%end%>
  <%end%>


  </div><!-- END OF CARD-GROUP -->


</main>

app/views/interests/index.html.erb
<h1>Interests</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Description</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_interestt.each do |interest| %>
      <tr>
        <td><img src='<%= interest.interest.image %>' style='width: 50px'></td>
        <td><%= interest.interest.title %></td>
        
        <td><%= link_to 'Show', interest %></td>
        <td> <%= link_to 'Destroy', user_interestt_path(interest), method: :delete, data: { confirm: 'Are you sure?' } %> </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/interests/new.html.erb
<div class="card-columns container">
<div>
<%= form_for @interest, url:{action: "create"} do |f|%>
  <%= f.label :title%>
  <%= f.text_field :title, id: "title"%>
  <%= f.hidden_field :link, id: "link"%>
  <%= f.hidden_field :description, id: "description"%>
  <%= f.hidden_field :image, id: "image"%>
 <%# <input type="text" id="myInput"> %>

<script type="text/javascript">

var config = {
  'limit': 10,
  'languages': ['en'],
//  'languages': ['en', 'ar'],

  // 'types': ['Person', 'Movie'],
  // 'types': ['Song'],
  // 'maxDescChars': 100,
};
config['selectHandler'] = function(e) {
  document.getElementById("link").value = e.row.id;
  // document.getElementById("s_description").value = e.row.description;
  document.getElementById("description").value = e.row.rc;
  document.getElementById("image").value = e.row.Je;
  // document.getElementById("image").value = e.row.rc;
console.log(e);

  



};
config['highlightHandler'] = function(e) {
//   alert(e.row.name + ' highlighted');
};

  KGSearchWidget("AIzaSyCeT542FtLDFZaSYrCBH6rXgt4_AagjMzQ", document.getElementById("title"), config);
</script>
<%= f.submit %>
<%end%>
</div>
<%# <input type="text" id="myInput">

<script type="text/javascript">

var config = {
  'limit': 10,
  'languages': ['en', 'ar'],
  // 'types': ['Person', 'Movie'],
  // 'types': ['Song'],
  'maxDescChars': 100,
};
config['selectHandler'] = function(e) {
//   alert(e.row.name + ' selected');
console.log(e.row.id);


};
config['highlightHandler'] = function(e) {
//   alert(e.row.name + ' highlighted');
};

  KGSearchWidget("AIzaSyCeT542FtLDFZaSYrCBH6rXgt4_AagjMzQ", document.getElementById("myInput"), config);
</script> %>



<div>
<h1>Interests</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user_interestt.each do |interest| %>
      <tr>
        <td><img src='<%= interest.interest.image %>' style='width: 50px'></td>
        <td><%= interest.interest.title %></td>
        
        <td><%= link_to 'Show', interest %></td>
        <td> <%= link_to 'Destroy', user_interestt_path(interest), method: :delete, data: { confirm: 'Are you sure?' } %> </td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeMatch!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link type="text/css" rel="stylesheet" href="https://www.gstatic.com/knowledge/kgsearch/widget/1.0/widget.min.css">
 <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://www.gstatic.com/knowledge/kgsearch/widget/1.0/widget.min.css">
<style>
  .kge-search-picker {
    width: 350px;
  }
</style>
<script type="text/javascript" src="https://www.gstatic.com/knowledge/kgsearch/widget/1.0/widget.min.js"></script>


  </head>

  <body>


<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="#" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href= <%= root_path %> class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>WeMatch</strong>
          </a>

    <% if user_signed_in? %>
    <%= link_to current_user.name, new_interest_path %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
    <%# <%= link_to "Sign up", new_user_registration_path %>
    <li class="nav-item" style="list-style-type: none;">
     <%= link_to "Sign in", new_user_session_path , :class=>"align-self-end"%>
    </li>
    <% end %>


          <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button> %>
        </div>
      </div>
</header>
<!-- NAV START HERE--->


<!-- NAV END HERE -->
<div class="alert alert-success" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%# <strong>Success!</strong> You have been signed in successfully! %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= yield %>

        <footer class="text-muted page-footer font-small unique-color-dark pt-4" style="margin-bottom:0">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Made with &hearts; for you by  &copy; WeMatch!</p>
        <p><a href="../../">Privacy Policy</a> | <a href="../../">Terms of Services</a>.</p>
      </div>
    </footer>

  </body>
</html>

app/views/user_interestts/show.html.erb
<div> 
      <img src='<%= @interestx.interest.image %>' style='width: 500px'>

              <div class="card ">
        <%if @interestx.interest.image == "undefined" %>
                <h5 class="card-title"><%= @interestx.interest.title %></h5>
                <blockquote class="blockquote mb-0">
                <p class="card-text"><%= @interestx.interest.description %></p>

                </blockquote>
          
        <%else%>
            <img class="card-img-top" src="<%= @interestx.interest.image %>" alt="Card image cap" style='width: 50%'>
            <div class="card-body">
                <h5 class="card-title"><%= @interestx.interest.title %></h5>
                <p class="card-text"><%= @interestx.interest.description %></p>
              </div>
       
        <%end%>
   </div>
   </div>